image: docker:latest

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $IMAGE_TAG .

deploy:
  stage: deploy
  tags:
    - docker
  variables:
    RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker tag $IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
  only:
    - master
